### ISSUE TITLE
Home page refresh speed

### ISSUE THREAD

**Issue by ViesLink** [Guilehm/project-management-system#7]
http://127.0.0.1:8000/  → **It takes up to several minutes to refresh the page**
http://127.0.0.1:8000/admin/login/?next=/admin/  → **The response of this page is very fast**

Is there a need to load some static resources from the Internet, which causes the problem of slow home page refresh。

**Comment by Guilehm** [comment]
@ViesLink unfortunately i currently have no time to work on this project.
But I appreciate your contact, and if you have availability, it will be a pleasure to accept a PR with corrections.

**Comment by ViesLink** [comment]
@Guilehm Thanks for the reply, I'll give it a try
